import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`bg-green-500 ${geistSans.variable} ${geistMono.variable} antialiased font-[family-name:var(--font-geist-sans)]`}
      >
        <div className="flex flex-col w-screen h-auto m-auto">
          <div className="bg-blue-600 relative flex flex-row justify-start items-center w-full h-10">
            <h1>logo</h1>
          </div>
          <div className="max-w-[1440px] mt-5 mx-auto">
            {children}</div>
        </div>
      </body>
    </html>
  );
}
